import os
from datetime import datetime
from src.db import get_connection

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "output")


def _severity_icon(severity: str) -> str:
    return {"CRITICAL": "[!!!]", "HIGH": "[!! ]", "MEDIUM": "[ ! ]", "LOW": "[   ]"}.get(severity, "[ ? ]")


def generate_report(run_id: int, validation_summary: dict, dataset_name: str) -> str:
    """
    Pull run data from the database and write the QA report to file.
    Returns the path to the generated report.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    conn = get_connection()

    # Fetch run metadata
    run = conn.execute(
        "SELECT * FROM qa_test_runs WHERE run_id = ?", (run_id,)
    ).fetchone()

    # Fetch all issues grouped by rule
    issues = conn.execute(
        """
        SELECT res.rule_code, res.claim_id, res.patient_id,
               res.field_name, res.field_value, res.issue_detail,
               res.severity, qr.rule_name, qr.domain
        FROM qa_results res
        JOIN qa_rules qr ON res.rule_code = qr.rule_code
        WHERE res.run_id = ?
        ORDER BY
            CASE res.severity
                WHEN 'CRITICAL' THEN 1
                WHEN 'HIGH'     THEN 2
                WHEN 'MEDIUM'   THEN 3
                WHEN 'LOW'      THEN 4
            END,
            res.rule_code,
            res.claim_id
        """,
        (run_id,)
    ).fetchall()

    conn.close()

    # Build report lines
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = os.path.join(OUTPUT_DIR, f"qa_report_{ts}.txt")

    sev = validation_summary["severity_counts"]
    total = run["total_records"]
    flagged = run["fail_count"]
    clean = run["pass_count"]
    pass_rate = round(100.0 * clean / total, 1) if total else 0

    lines = []

    lines += [
        "=" * 72,
        "  HEALTHCARE CLAIMS DATA — QA VALIDATION REPORT",
        "=" * 72,
        f"  Run ID       : {run_id}",
        f"  Dataset      : {dataset_name}",
        f"  Timestamp    : {run['run_timestamp']}",
        f"  Duration     : {run['run_duration_ms']} ms",
        f"  Status       : {run['run_status']}",
        "",
        "  SUMMARY",
        "  " + "-" * 40,
        f"  Total records loaded  : {total}",
        f"  Clean records         : {clean}  ({pass_rate}%)",
        f"  Records with issues   : {flagged}",
        f"  Total issues found    : {run['total_issues']}",
        "",
        "  ISSUES BY SEVERITY",
        "  " + "-" * 40,
        f"  {_severity_icon('CRITICAL')} CRITICAL : {sev.get('CRITICAL', 0):>4}  (data must NOT be promoted)",
        f"  {_severity_icon('HIGH')}     HIGH     : {sev.get('HIGH', 0):>4}  (investigate before next run)",
        f"  {_severity_icon('MEDIUM')}   MEDIUM   : {sev.get('MEDIUM', 0):>4}  (flag for analyst review)",
        f"  {_severity_icon('LOW')}      LOW      : {sev.get('LOW', 0):>4}  (informational)",
        "",
        "  ISSUES BY RULE",
        "  " + "-" * 40,
    ]

    for rule_code, count in sorted(validation_summary["issues_by_rule"].items()):
        if count > 0:
            lines.append(f"  {rule_code}  :  {count} issue(s) found")

    lines += ["", "=" * 72, "  DETAILED FINDINGS", "=" * 72, ""]

    # Group issues by rule
    current_rule = None
    for issue in issues:
        if issue["rule_code"] != current_rule:
            current_rule = issue["rule_code"]
            lines += [
                f"  {_severity_icon(issue['severity'])} {issue['rule_code']} — {issue['rule_name']}",
                f"  Domain: {issue['domain']} | Severity: {issue['severity']}",
                "  " + "-" * 68,
            ]

        lines += [
            f"  Claim     : {issue['claim_id']}",
            f"  Patient   : {issue['patient_id'] or 'N/A'}",
            f"  Field     : {issue['field_name']}  =  \"{issue['field_value']}\"",
            f"  Detail    : {issue['issue_detail']}",
            "",
        ]

    lines += [
        "=" * 72,
        "  END OF REPORT",
        f"  Generated by Healthcare Claims Data QA System",
        f"  Report saved to: {report_path}",
        "=" * 72,
    ]

    report_text = "\n".join(lines)

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_text)

    return report_path, report_text
